INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('samsung','S100','active',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('samsung','S200','active',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('LG','L100','inactive',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('HITACHI','H100','active',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('samsung','S900','inactive',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('sony','SS100','active',NOW());

INSERT INTO HOUSEHOLD_APPLIANCES(BRAND_NAME, MODEL_NAME, STATUS_NAME, DATE) VALUES('OGENERAL','O100','active',NOW());